### ISSUE TITLE
CSS for links, hrefs

### ISSUE THREAD

**Issue by NavinShrinivas** [homebrew-ec-foss/homebrew-internethome#12]
![2022-03-05_10-18](https://user-images.githubusercontent.com/42774281/156868399-ee669dd3-bc6f-41a4-b5b0-7f3afcfcd311.png)

Okay so yeah, those are links. We need to add something to CSS (tailwind classes possibly) to differentiate from the rest of the text, feel free to ask design team on how to make the links stand out. This has to be fixed here cus the design will be same across all posts.

**Comment by anirudhRowjee** [comment]
This has been fixed. Issue stale, hence closing.
