### ISSUE TITLE
Add Author Name in Post header

### ISSUE THREAD

**Issue by anirudhRowjee** [homebrew-ec-foss/homebrew-internethome#40]
Since the author information moved to the frontmatter, it is no longer a part of the text. Modify the post template to render the author name and link if present.

**Comment by Saksham-13** [comment]
![image](https://user-images.githubusercontent.com/88273114/163592870-f9c12b9c-ff46-4a57-b82e-792b7abf63b7.png)
Its there in the end.(is that what u meant)

**Comment by anirudhRowjee** [comment]
@Saksham-13 Not quite. I'd like the author's name and Link to be at the top of the page. I've implemented it, will push ASAP.
