### ISSUE TITLE
Turing Awaree Information Page

### ISSUE THREAD

**Issue by anirudhRowjee** [homebrew-ec-foss/homebrew-internethome#48]
we would welcome a blog post about the Turing Award given out by the ACM, along with a list of computer scientists who have won the award, in Chronological Order.

**Comment by inirah02** [comment]
I'd be interested in contributing to this issue!

**Comment by anirudhRowjee** [comment]
All the best!

**Comment by inirah02** [comment]
Title: Turing Awards by ACM
Date: '2022-08-06'
Tags: [Turing Awards, media]
Description: Want to add the Oscar equivalent of Computer Science to your vision board and hopefully, to your portfolio one day? Read on to know all about it. 
Name : Harini Anand
Link : https://docs.google.com/document/d/1pf7zhltQo9TA2tH9ia4WTfGXe_jENlzi9BPhYTXcxFA/edit?usp=sharing
