### ISSUE TITLE
Remove "Inner Circle" and "Outer Circle"

### ISSUE THREAD

**Issue by anirudhRowjee** [homebrew-ec-foss/homebrew-internethome#55]
Since Homebrew is an Open-Source community, we want to promote equality between all members. 

In the Members page, The HackerSpace Core Team and Moderators can be assigned a separate tag that makes the community more inclusive.

**Comment by anuragrao04** [comment]
just clearing up, we want the two tabs 'inner' and 'outer' circle to be removed and all participants come under a common tag 'members' or something like that?

**Comment by anirudhRowjee** [comment]
yes.

**Comment by anuragrao04** [comment]
check out PR #57  :)

**Comment by anuragrao04** [comment]
hey, why was the PR reverted? any changes?
